// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpw4AIME_8GjVNGzxHmCY0xoEJ85bB-9I',
    appId: '1:48529668066:web:9fb380450c3395b416ebbb',
    messagingSenderId: '48529668066',
    projectId: 'shoesapp-10ac9',
    authDomain: 'shoesapp-10ac9.firebaseapp.com',
    storageBucket: 'shoesapp-10ac9.appspot.com',
    measurementId: 'G-04QHC3BMPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3kVn1bJgY_mh6fqLQDAGIOtpkj6YNP2o',
    appId: '1:48529668066:android:ed20eef56f0aa6c216ebbb',
    messagingSenderId: '48529668066',
    projectId: 'shoesapp-10ac9',
    storageBucket: 'shoesapp-10ac9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3_LbBOCfJe44KLk4CniEhZIEw-m7wEA8',
    appId: '1:48529668066:ios:f825a247f4a5807116ebbb',
    messagingSenderId: '48529668066',
    projectId: 'shoesapp-10ac9',
    storageBucket: 'shoesapp-10ac9.appspot.com',
    iosBundleId: 'com.example.shoeShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3_LbBOCfJe44KLk4CniEhZIEw-m7wEA8',
    appId: '1:48529668066:ios:f825a247f4a5807116ebbb',
    messagingSenderId: '48529668066',
    projectId: 'shoesapp-10ac9',
    storageBucket: 'shoesapp-10ac9.appspot.com',
    iosBundleId: 'com.example.shoeShopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpw4AIME_8GjVNGzxHmCY0xoEJ85bB-9I',
    appId: '1:48529668066:web:170e13f3ce9a63b716ebbb',
    messagingSenderId: '48529668066',
    projectId: 'shoesapp-10ac9',
    authDomain: 'shoesapp-10ac9.firebaseapp.com',
    storageBucket: 'shoesapp-10ac9.appspot.com',
    measurementId: 'G-K168NFMJGT',
  );
}
